### ISSUE TITLE
Needs contributors for porting the code in PHP and JavaScript into C#

### ISSUE THREAD

**Issue by thangchung** [thangchung/clean-code-dotnet#1]
Actually, I'm quite busy at the moment so I'm hard to contribute more in the repo (come back later), but I recognized that this repo is a good help for the community. If anyone is willing to support that would be great.

**Comment by ngohungphuc** [comment]
I think we can close this issue

**Comment by thangchung** [comment]
@ngohungphuc Agree 👍
