### ISSUE TITLE
Consider c# region directive in Avoid positional markers section

### ISSUE THREAD

**Issue by avitsidis** [thangchung/clean-code-dotnet#11]
Clean code tell us to [Avoid positional markers](https://github.com/thangchung/clean-code-dotnet#avoid-positional-markers). I totally agree with that but as we are in a dotnet/c# specific version of clean code should the Readme have a [region directive](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-region) snippet in the bad section?

If you agree with that, I would be happy to contribute and send you a pull request with this code snippet.

**Comment by thangchung** [comment]
I have commented in #14
