### ISSUE TITLE
Add a Testing structure proposal in testing section

### ISSUE THREAD

**Issue by avitsidis** [thangchung/clean-code-dotnet#29]
It could be a good idea to add a test structure proposal in the testing section. I was thinking to something like the phil haacked proposition : name test class like {Class}Test, create sub test classes with method name and then name test with the expectedResult.

I can write a pull request with an implementation inspired from phil haacked pattern (https://haacked.com/archive/2012/01/02/structuring-unit-tests.aspx/)

**Comment by thangchung** [comment]
Close, because of long time no react in this issue. Feel free to re-open if you think that need
