### ISSUE TITLE
Use consistent capitalization should reference Microsoft conventions

### ISSUE THREAD

**Issue by avitsidis** [thangchung/clean-code-dotnet#31]
IMHO, A link to [Microsoft Naming guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/naming-guidelines) should be provided in the Use consistent capitalization. It could help developers to all use the same convention.

**Comment by thangchung** [comment]
@avitsidis Thank you for a lot of attention from you in this repo. I have read the Microsoft Naming guidelines, and also noticed that it published a long time ago. Do you know if it still valids for all the conventions so far?
