### ISSUE TITLE
The _tokenizer and _lexer properties in BetterJSAlternative class must change with own class types.

### ISSUE THREAD

**Issue by themekware** [thangchung/clean-code-dotnet#33]
class BetterJSAlternative
{
    private string _tokenizer; // private Tokenizer _tokenizer;
    private string _lexer; // private Lexer _lexer;

    public BetterJSAlternative(Tokenizer tokenizer, Lexer lexer)
    {
        _tokenizer = tokenizer;
        _lexer = lexer;
    }

    public string Parse(string code)
    {
        var tokens = _tokenizer->Tokenize(code);
        var ast = _lexer.Lexify(tokens);
        foreach (var node in ast)
        {
            // parse...
        }
    }
}

**Comment by thangchung** [comment]
Yeah. I haven't finished to translate all the js code to csharp code yet. If you're willing to help that would be great, mate.

**Comment by thangchung** [comment]
Close it for now. Feel free to re-open if you have more concerns.
