### ISSUE TITLE
Example error in [Dependency Inversion Principle (DIP)]/[Good] section

### ISSUE THREAD

**Issue by dust63** [thangchung/clean-code-dotnet#38]
```
public interface Employee
{
    void Work();
}
```

you need to call you interface IEmployee for a better comprehension.

```
public interface IEmployee
{
    void Work();
}
```

**Comment by avitsidis** [comment]
I totally agree! .Net interfaces always start with an I. Code samples should follow this rule

**Comment by thangchung** [comment]
Fixed. Thank you so much for your findings 👍
