### ISSUE TITLE
Some confusion regarding the code example in "Don't write to global functions"

### ISSUE THREAD

**Issue by user3301** [thangchung/clean-code-dotnet#57]
The code example given showcases a good practice for acquiring a configuration from a string array:
`public string[] Config()
{
    return  [
        "foo" => "bar",
    ]
}`
just wondering is this a legit C# syntax as I never seen it before? or just some pseudocode for the demonstration purpose?

**Comment by thangchung** [comment]
@user3301 I believe that it comes from PHP. I will fix it. Thank you for your findings
