### ISSUE TITLE
"Avoid side effects" Example is not right

### ISSUE THREAD

**Issue by Gante82** [thangchung/clean-code-dotnet#65]
The code for the **"Avoid side effects"** example is not right. In addition to the quotes being reversed, I think this example does not work in C# because Split returns **string[]** and this cannot be assigned to the variable **name**. This made sense for JavaScript but not for C#.

What do you think about this other example?

**Bad:**

```
var number = 7;

public int AddTwo()
{
	return number = number + 2;
}

AddTwo();

Console.PrintLine(number); // 9
```

**Good:**

```
public int AddTwo(int number)
{
	return number + 2;
}

var number = 7;
var newNumber = AddTwo(number);

Console.PrintLine(number); // 7
Console.PrintLine(newNumber); // 9
```

**Comment by ugurozturk** [comment]
For C# Just adding [] fixed it. Nothing more, so the example was correct i guess.

```diff
-public string SplitIntoFirstAndLastName(string name)
+public string[] SplitIntoFirstAndLastName(string name)
{
    return name.Split(" ");
}

var name = 'Ryan McDermott';
var newName = SplitIntoFirstAndLastName(name);

Console.PrintLine(name); // 'Ryan McDermott';
Console.PrintLine(newName); // ['Ryan', 'McDermott'];
```

**Comment by dmitryvhf** [comment]
> Nothing more, so the example was correct i guess.
Nope. Not found side-effect. For side-effect example we need show first value again. There must be new value.

**Comment by thangchung** [comment]
Thank you all. Feel free to re-open if it is still not make sense!
