### ISSUE TITLE
Hungarian notation

### ISSUE THREAD

**Issue by sheeit** [thangchung/clean-code-dotnet#9]
[Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) does not mean what you seem to imply it means in the README.

I think what your trying to say is “Use [camelCase](https://en.wikipedia.org/wiki/Camel_case) for variable names and function parameters.”

**Comment by thangchung** [comment]
@sheeit That is our team mistakes. I've fixed it. The list is still in process so if you find out something like that, please let us know. Thank again for your correction 👍
